swagger: '2.0'
info:
  version: '0.1.0'
  title: Projet Two API
  description: An API to demonstrate Swagger
host: localhost:8282
basePath: /api
schemes:
  - http
paths:
  /videogames:
    post:
      security:
        - Bearer: []
      description: create a video game
      operationId: createVideogame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: videogame
          in: body
          required: true
          schema:
            $ref: '#/definitions/Videogame'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      security:
        - Bearer: []
      description: get the list of all video games
      operationId: getVideogames
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Videogame'

    delete:
      security:
        - Bearer: []
      description: delete a videogame using his id
      operationId: deleteVideogame
      produces:
        - application/json
      parameters:
        - name: videogames
          in: body
          description: "videogame to delete"
          required: true
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
      responses:
        200:
          description: 'Delete done'
          schema:
            $ref: '#/definitions/Videogame'
        400:
          description: "Invalid videogame supplied"
        404:
          description: "Videogame not found"

securityDefinitions:
  Bearer:
    description: "Give the token at each user"
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  Videogame:
    type: object
    properties:
      id:
        type: integer
      kind:
        type: string
      name:
        type: string
      supportedOn:
        type: string




