swagger: '2.0'
info:
  version: '0.1.0'
  title: Projet Two API
  description: An API to demonstrate Swagger
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /videogame:
    post:
      description: create a video game
      operationId: createVideogame
      consumes:
        - application/json
      parameters:
        - name: videogame
          in: body
          required: true
          schema:
            $ref: '#/definitions/Videogame'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all video games
      operationId: getVideogames
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Videogame'
    patch:
      description: update a videogame
      operationId: updateVideogame
      produces:
        - application/json
      responses:
        '200':
          description: success update
          schema:
            type: array
            items:
              $ref: '#/definitions/Videogame'
definitions:
  Videogame:
    type: object
    properties:
      kind:
        type: string
      name:
        type: string
      console:
        supportedOn: string